---
title: "C. elegans visualizer"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---


```{r setup, include = FALSE}
library(flexdashboard)
library(igraph)
library(threejs)
library(networkD3)
library(readxl)
library(dplyr)
k <- readxl::read_xls("konektom.xls", sheet = "Connectome")
colnames(k) <- c('from', 'to', 'weight')

p <- simpleNetwork(k,
                   height = NULL,
                   width = NULL, 
                   Source = 1,
                   Target = 2,
                   linkDistance = 20,
                   charge = -100,
                   fontSize = 15,
                   fontFamily = "sans-serif",
                   linkColour = "#8d99ae",
                   nodeColour = "#2b2d42",
                   opacity = 0.5,
                   zoom = T
)
network <- graph_from_edgelist(as.matrix(k[,1:2]), dir = T)

vert_names <- c(k$from, k$to) %>% unique() 
colors <- colorspace::heat_hcl(length(vert_names))
names(colors) = vert_names
```

```{r}
graphjs(network,
        bg = 'white',
        vertex.size = sqrt(k$weight)/5,
        vertex.shape = "circle",
        vertex.color = as.vector(colors[vert_names]),
        vertex.label = k$from,
        edge.width = 1,
        edge.color = "#000000",
        edge.alpha = 0.1)
```

```{r include = FALSE}
src <- k$from
target <- k$to
networkData <- data.frame(src, target, stringsAsFactors = FALSE)

nodes <- data.frame(name = unique(c(src, target)), stringsAsFactors = FALSE)
nodes$id <- 0:(nrow(nodes) - 1)

edges <- networkData %>%
   left_join(nodes, by = c("src" = "name")) %>%
   select(-src) %>%
   rename(source = id) %>%
   left_join(nodes, by = c("target" = "name")) %>%
   select(-target) %>%
   rename(target = id)

edges$width <- sample(c(1,2,5, 10), 3954, replace = T)
 
nodes$group <- ifelse(nodes$name %in% src, "lions", "tigers")
nodes$size <- sample(c(1,6,5,17), 397, replace = T)

forceNetwork(Links = edges, Nodes = nodes, 
             Source = "source",
             Target = "target",
             NodeID ="name",
             Nodesize = 'size',
             Group = "group",
             Value = "width",
             opacity = 0.9,
             zoom = TRUE)
```

```{r include = FALSE}
a <- readxl::read_xls("NeuronConnect.xls")
b <- readxl::read_xls("NeuronType.xls")
```

